
<style type="text/css">
.centre {  align: center;}
.myalg {  text-align: left ! important;}
.myald {  text-align: right;}
.myalc {  text-align: center;}
.cl1 {color:#000000;}
.cl2 {color:#4c4c4c;}
.cl3 {color:#000000;}
.t1 { font-size: 85.5%; }
.t2 { font-size: 99.5%; font-weight bold ;}
.gras {font-weight bold ;}
.m1 { margin: 1em 10px; padding: 1.6em 30px;}
.b0 { border: none;}
.b1 { border: 1px solid  #969696;}
.b2 {border:solid 10px white;}
.w1 { width: 99%;}
.w75 { width: 75%;}
.w95 { width: 95%;}
.w90 { width: 90%;}
.w100 { width: 100%;}
.bg1{ background: #ececec;}
.bg2{ background: #969696;}
#data tr th {border:solid 7px #ececec;color:#000000;background:#ececec;align: center;font-size:13px;}
#data tr td {border:solid 7px white;color:#000000;text-align: right;font-size:13px;}
#data tr {background:white;}
td.myalg {  text-align: left ! important;}
</style>
<page>
<?php include('entete.phtml');?>

<table class="w1 b0" cellspacing="1mm" cellpadding="0">
		<tr>	<td class="myalg cl3 t2" style="width: 5%"></td>
			<td class="myalg cl1 t2" >EXERCICE :</td>
			<td class="myalg cl3 t2" ><?php echo $this->exercice ?></td>
		</tr>
		<tr>	<td class="myalg cl3 t2" style="width: 5%"></td>
			<td class="myalg cl1 t2" >MOIS DE &nbsp;&nbsp;&nbsp;:</td>
			<td class="myalg cl3 t2" ><?php echo $this->nmois ?></td>
		</tr>
</table>
<table class="w90 b0" cellspacing="2mm" cellpadding="0" align="center">
		<tr><td class="myalc w1 cl3 t2 bg1"><?php echo $this->titre ?></td></tr>
</table>
<br/>
<!-- ==================================================================================================================================== -->
<table id="data" cellspacing="0.2mm" class="bg2 w100" align="center"> 
	<tr><th>Communes</th><th>Anterieur au mois</th><th>Pendant le mois</th><th>Cumul</th></tr>
							<?php
  									$tan=0; $tmo=0; $tcu=0; 
									foreach($this->anict as $a){
										$can='can_'.$a->a_c_num;$$can=0;
										$ccu='ccu_'.$a->a_c_num;$$ccu=0;
									}
									$m=$this->vmois; 
									for($i=1;$i<=$this->mois;$i++){
										switch($i){
											case 1: $vmois='a_jan';break;
											case 2: $vmois='a_fev';break;
											case 3: $vmois='a_mar';break;
											case 4: $vmois='a_avr';break;
											case 5: $vmois='a_mai';break;
											case 6: $vmois='a_juin';break;
											case 7: $vmois='a_jui';break;
											case 8: $vmois='a_aou';break;
											case 9: $vmois='a_sep';break;
											case 10: $vmois='a_oct';break;
											case 11: $vmois='a_nov';break;
											default: $vmois='a_dec';
										}
										foreach($this->anict as $a){
										$m=$a->$vmois;
										$can='can_'.$a->a_c_num;
										$ccu='ccu_'.$a->a_c_num;
										$$ccu=$m+$$can;
										//$tan+=$$can; $tmo+=$m; $tcu+=$$ccu;
										//$tan+=$$can; $tmo+=$m; $tcu+=$$ccu;
										//$$can+=$m;
										if($i< $this->mois) $$can+=$m;
										}
									}
										foreach($this->anict as $a){
										$n=$this->vmois;
										$m=$a->$n;
										$can='can_'.$a->a_c_num;
										$ccu='ccu_'.$a->a_c_num;
										$tan+=$$can; $tmo+=$m; $tcu+=$$ccu;
											echo '<tr>';
											echo '<td class="myalg">'.$a->a_c_nom.'</td>';
											echo '<td>'.($$can==0 ?'':number_format($$can,0,' ',' ')).'</td>';
											echo '<td>'.($m==0 ?'':number_format($m,0,' ',' ')).'</td>';
											echo '<td>'.($$ccu==0 ?'':number_format($$ccu,0,' ',' ')).'</td>';
											echo '</tr>';
										}
										echo '<tr>';
										echo '<th class="myalg">Total</th>';
										echo '<th class="myald">'.number_format($tan,0,' ',' ').'</th>';
										echo '<th class="myald">'.number_format($tmo,0,' ',' ').'</th>';
										echo '<th class="myald">'.number_format($tcu,0,' ',' ').'</th>';
										echo '</tr>';
							?>
							</table>
<!-- ==================================================================================================================================== -->
<br/><br/><br/><br/>

<?php include('pied.phtml');?>

</page>
